require 'spec_helper'
require 'ec2ssh/cli'

describe Ec2ssh::CLI do
  let(:cli) do
    described_class.tap do |cls|
      cls.class_eval do
        no_tasks do
          def hosts
            [
              {:host => 'db-01', :dns_name => 'ec2-1-1-1-1.ap-northeast-1.ec2.amazonaws.com'},
              {:host => 'db-02', :dns_name => 'ec2-1-1-1-2.ap-northeast-1.ec2.amazonaws.com'},
            ]
          end
        end
      end
    end
  end
  let(:ssh_config_path) do
    path = tmp_dir.join('ssh_config')
    path.open('w') {|f| f.write <<-END }
Host foo.bar.com
  HostName 1.2.3.4
    END
    path
  end
  let(:ssh_config_string) { ssh_config_path.read }

  around do |example|
    Timecop.freeze(Time.local(2013,1,1,0,0,0)) { example.call }
  end

  subject { ssh_config_string }

  describe '#init' do
    before do
      silence(:stdout) { cli.start %W[init --path #{ssh_config_path}] }
    end

    it { should eq(<<-END) }
Host foo.bar.com
  HostName 1.2.3.4
### EC2SSH BEGIN ###
# Generated by ec2ssh http://github.com/mirakui/ec2ssh
# DO NOT edit this block!
# Updated 2013-01-01 00:00:00 +0900

### EC2SSH END ###
END
  end

  describe '#update' do
    before do
      silence(:stdout) do
        cli.start %W[init --path #{ssh_config_path}]
        cli.start %W[update --path #{ssh_config_path}]
      end
    end

    it { should eq(<<-END) }
Host foo.bar.com
  HostName 1.2.3.4
### EC2SSH BEGIN ###
# Generated by ec2ssh http://github.com/mirakui/ec2ssh
# DO NOT edit this block!
# Updated 2013-01-01 00:00:00 +0900
Host db-01
  HostName ec2-1-1-1-1.ap-northeast-1.ec2.amazonaws.com
Host db-02
  HostName ec2-1-1-1-2.ap-northeast-1.ec2.amazonaws.com

### EC2SSH END ###
END
  end

  describe '#remove' do
    before do
      silence(:stdout) do
        cli.start %W[init --path #{ssh_config_path}]
        cli.start %W[update --path #{ssh_config_path}]
        cli.start %W[remove --path #{ssh_config_path}]
      end
    end

    it { should eq(<<-END) }
Host foo.bar.com
  HostName 1.2.3.4
END
  end
end
