require 'spec_helper'
require 'ec2ssh/cli'
require 'ec2ssh/dotfile'
require 'pry'
describe Ec2ssh::CLI do
  before(:all) do
    Ec2ssh::Hosts.tap do |cls|
      cls.class_eval do
        def instances region
          [
            {:tag_set => [{:key=>"Name", :value=>"db-01"}],
             :instance_id => 'i-01234560',
             :dns_name => 'ec2-1-1-1-1.ap-northeast-1.ec2.amazonaws.com'},
            {:tag_set => [{:key=>"Name", :value=>"db-02"}],
             :instance_id => 'i-01234561',
             :dns_name => 'ec2-1-1-1-2.ap-northeast-1.ec2.amazonaws.com'},
            {:tag_set => [{:key=>"Name", :value=>"private-web-as"}],
             :instance_id => 'i-01234562',
             :private_dns_name => 'ec2-1-1-1-2.ap-northeast-1.compute.internal'},
            {:tag_set => [{:key=>"Name", :value=>"private-web-as"}],
             :instance_id => 'i-01234563',
             :private_dns_name => 'ec2-1-1-1-3.ap-northeast-1.compute.internal'},
          ]
        end
      end
    end
  end
  before do
    File.delete(dotfile_path) if File.exist?(dotfile_path)
  end
  let(:cli) { described_class }
  let(:ssh_config_path) do
    path = tmp_dir.join('ssh_config')
    path.open('w') {|f| f.write <<-END }
Host foo.bar.com
  HostName 1.2.3.4
    END
    path
  end
  let(:ssh_config_string) { ssh_config_path.read }
  let(:dotfile_path) do
    tmp_dir.join('dot.ec2ssh')
  end

  around do |example|
    tz = ENV['TZ']
    ENV['TZ'] = 'UTC'
    Timecop.freeze(Time.local(2013,1,1,0,0,0)) { example.call }
    ENV['TZ'] = tz
  end

  subject { ssh_config_string }

  describe '#init' do
    before do
      silence(:stdout) { cli.start %W[init --path #{ssh_config_path} --dotfile #{dotfile_path}] }
    end

    it { should eq(<<-END) }
Host foo.bar.com
  HostName 1.2.3.4
### EC2SSH BEGIN ###
# Generated by ec2ssh http://github.com/mirakui/ec2ssh
# DO NOT edit this block!
# Updated 2013-01-01T00:00:00+00:00

### EC2SSH END ###
    END
  end

  describe '#update' do
    context 'no use_private_dns option' do
      before do
        silence(:stdout) do
          cli.start %W[init --path #{ssh_config_path} --dotfile #{dotfile_path}]
          cli.start %W[update --path #{ssh_config_path} --dotfile #{dotfile_path}]
        end
      end

      it { should eq(<<-END) }
Host foo.bar.com
  HostName 1.2.3.4
### EC2SSH BEGIN ###
# Generated by ec2ssh http://github.com/mirakui/ec2ssh
# DO NOT edit this block!
# Updated 2013-01-01T00:00:00+00:00
# section: default
Host db-01.ap-northeast-1
  HostName ec2-1-1-1-1.ap-northeast-1.ec2.amazonaws.com
  
Host db-02.ap-northeast-1
  HostName ec2-1-1-1-2.ap-northeast-1.ec2.amazonaws.com
  


### EC2SSH END ###
      END
    end

    context 'with use_private_dns option' do
      before do
        silence(:stdout) do
          cli.start %W[init --path #{ssh_config_path} --dotfile #{dotfile_path}]
          cli.start %W[update --path #{ssh_config_path} --dotfile #{dotfile_path} --use-private-dns]
        end
      end

      it { should eq(<<-END) }
Host foo.bar.com
  HostName 1.2.3.4
### EC2SSH BEGIN ###
# Generated by ec2ssh http://github.com/mirakui/ec2ssh
# DO NOT edit this block!
# Updated 2013-01-01T00:00:00+00:00
# section: default
Host private-web-as.i-01234562.ap-northeast-1
  HostName ec2-1-1-1-2.ap-northeast-1.compute.internal
  
Host private-web-as.i-01234563.ap-northeast-1
  HostName ec2-1-1-1-3.ap-northeast-1.compute.internal
  


### EC2SSH END ###
      END
    end
  end

  describe '#update with aws-keys option' do
    before do
      silence(:stdout) do
        cli.start %W[init --path #{ssh_config_path} --dotfile #{dotfile_path}]
      end
      dotfile = Ec2ssh::Dotfile.load(dotfile_path)
      dotfile['aws_keys']['key1'] = {
        'access_key_id' => 'ACCESS_KEY_ID',
        'secret_access_key' => 'SECRET_ACCESS_KEY'
      }
      @output = capture(:stdout) do
        cli.start %W[update --path #{ssh_config_path} --dotfile #{dotfile_path} --aws-key #{keyname}]
      end
    end

    subject { @output }

    context do
      let(:keyname) { 'default' }
      it { should =~ /Updated 2 hosts/ }
      it { should =~ /# section: default/ }
    end

    context do
      let(:keyname) { 'key1' }
      it { should =~ /Updated 2 hosts/ }
      it { should =~ /# section: key1/ }
    end

    context do
      let(:keyname) { 'key2' }
      it { should_not =~ /^Updated 2 hosts/ }
    end
  end

  describe '#update with aws-keys option in multiple times' do
    before do
      silence(:stdout) do
        cli.start %W[init --path #{ssh_config_path} --dotfile #{dotfile_path}]
      end
      dotfile = Ec2ssh::Dotfile.load(dotfile_path)
      dotfile['aws_keys']['key1'] = {
        'access_key_id' => 'ACCESS_KEY_ID',
        'secret_access_key' => 'SECRET_ACCESS_KEY'
      }
      dotfile['aws_keys']['key2'] = {
        'access_key_id' => 'ACCESS_KEY_ID',
        'secret_access_key' => 'SECRET_ACCESS_KEY'
      }
      @output = capture(:stdout) do
        cli.start %W[update --path #{ssh_config_path} --dotfile #{dotfile_path} --aws-key key1]
        cli.start %W[update --path #{ssh_config_path} --dotfile #{dotfile_path} --aws-key #{keyname}]
      end
    end

    subject { @output }

    context 'when updated by the same key' do
      let(:keyname) { 'key1' }
      it { subject.should     =~ /# section: key1/ }
      it { subject.should_not =~ /# section: key2/ }
    end

    context 'when updated by different key' do
      let(:keyname) { 'key2' }
      it { subject.should =~ /# section: key1/ }
      it { subject.should =~ /# section: key2/ }
    end
  end

  describe '#remove' do
    before do
      silence(:stdout) do
        cli.start %W[init --path #{ssh_config_path} --dotfile #{dotfile_path}]
        cli.start %W[update --path #{ssh_config_path} --dotfile #{dotfile_path}]
        cli.start %W[remove --path #{ssh_config_path} --dotfile #{dotfile_path}]
      end
    end

    it { should eq(<<-END) }
Host foo.bar.com
  HostName 1.2.3.4
    END
  end
end
